Repository TheBiggerGuy/com.chelsislotten.www, pull requests merged in 2021-07, with the labels that each got.

#53 Better align homepage headshot
  site/assets/scss/main.scss
  site/content/_index.md
  site/layouts/index.html
  site/layouts/shortcodes/col.html
  site/layouts/shortcodes/img.html
  site/layouts/shortcodes/row.html
Labels: enhancement

#55 Move CV button
  site/content/about/index.md
Labels: enhancement

#57 Correct the use of Markdown shortcodes
  site/content/_index.md
  site/content/portfolio/enchanted/index.md
  site/content/portfolio/museum/index.md
  site/content/portfolio/phd/index.md
  site/content/portfolio/podcast/index.md
  site/content/portfolio/presentations/index.md
  site/content/portfolio/publications/index.md
  site/layouts/index.html
  site/layouts/shortcodes/col.html
  site/layouts/shortcodes/row.html
Labels: enhancement

#58 Add custom image markdown template
  site/content/portfolio/museum/index.md
  site/layouts/_default/_markup/render-image.html
  site/layouts/_default/single.html
  site/layouts/partials/img.html
  site/layouts/portfolio/list.html
Labels: enhancement

#59 Fix non circle images
  site/layouts/index.html
Labels: bug

#60 Convert Personas to HTML
  site/assets/scss/main.scss
  site/assets/svg/noun_Avatar_girl_3345335.svg
  site/assets/svg/noun_Avatar_man_3345340.svg
  site/assets/svg/noun_Female Scientist_3841948.svg
  site/assets/svg/noun_Old Man Avatar_2643376.svg
  site/assets/svg/noun_girl_child_avatar_2509974.svg
  site/assets/svg/noun_teacher_avatar_2509967.svg
  site/content/portfolio/enchanted/Primary_persona.png
  site/content/portfolio/enchanted/index.md
  site/content/portfolio/enchanted/secondary_persona.png
  site/content/portfolio/museum/index.md
  site/content/portfolio/museum/primary_user_persona.png
  site/content/portfolio/museum/secondary_user_personna.png
  site/content/portfolio/podcast/Primary_user.png
  site/content/portfolio/podcast/Secondary_user.png
  site/content/portfolio/podcast/index.md
  site/layouts/shortcodes/persona.html
  thenounproject/README.md
  thenounproject/noun_Avatar_girl_3345335.svg
  thenounproject/noun_Avatar_man_3345340.svg
  thenounproject/noun_Female Scientist_3841948.svg
  thenounproject/noun_Old Man Avatar_2643376.svg
  thenounproject/noun_girl_child_avatar_2509974.svg
  thenounproject/noun_teacher_avatar_2509967.svg
Labels: enhancement

#61 Fix carousel image aspect
  site/assets/scss/main.scss
  site/content/portfolio/museum/index.md
Labels: bug

#63 Add food waste portfolio
  .gitignore
  site/assets/svg/noun_Woman avatar_2643369.svg
  site/assets/svg/noun_backpacker avatar_2643424.svg
  site/assets/svg/noun_teenager avatar_2643403.svg
  site/content/portfolio/enchanted/index.md
  site/content/portfolio/food_waste/Hi_fi_prototype.png
  site/content/portfolio/food_waste/Wireframes_Healthy_app.png
  site/content/portfolio/food_waste/aaalogo_small.png
  site/content/portfolio/food_waste/affinity_diagram.png
  site/content/portfolio/food_waste/customize_page.png
  site/content/portfolio/food_waste/home_screen.png
  site/content/portfolio/food_waste/index.md
  site/content/portfolio/food_waste/intro_screen.png
  site/content/portfolio/food_waste/recipe_page.png
  site/content/portfolio/food_waste/results_page.png
  site/content/portfolio/food_waste/search_screen.png
  site/content/portfolio/food_waste/shopping_list_page.png
  site/content/portfolio/food_waste/style_guide.png
  site/content/portfolio/museum/index.md
  site/layouts/_default/_markup/render-link.html
  site/layouts/partials/img.html
  site/layouts/shortcodes/persona.html
  thenounproject/noun_Woman avatar_2643369.svg
  thenounproject/noun_backpacker avatar_2643424.svg
  thenounproject/noun_teenager avatar_2643403.svg
Labels: enhancement

#64 Fix double col
  site/layouts/shortcodes/row.html
Labels: bug

#65 Make the homepage images linkable
  site/layouts/index.html
Labels: enhancement

#67 Fix columns in portfolios
  site/content/portfolio/food_waste/index.md
  site/content/portfolio/podcast/index.md
Labels: bug

#75 Fix home alignment
  site/layouts/shortcodes/col.html
  site/layouts/shortcodes/row.html
Labels: bug, enhancement
